# Generated by Django 3.2.8 on 2021-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weeks_of_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
