# Generated by Django 3.2.8 on 2021-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20211215_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='weeks_of_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
