# Generated by Django 3.2.8 on 2021-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='weeks_of_plan',
            new_name='plan_duration',
        ),
        migrations.AddField(
            model_name='workout',
            name='equipment_required',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workout',
            name='weekly_checkin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
