# Generated by Django 3.2.8 on 2021-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workoutreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutreview',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Workout Reviews'},
        ),
        migrations.AddField(
            model_name='workoutreview',
            name='review_title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='workoutreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
