# Generated by Django 3.2.8 on 2021-12-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20211229_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutreview',
            old_name='user_profile',
            new_name='user',
        ),
    ]
